# Show virtual keyboard in portrait, hide in landscape
$keyboard = wvkbd-mobintl

spin = eDP-1, left-up, exec, killall $keyboard && $keyboard
spin = eDP-1, right-up, exec, killall $keyboard && $keyboard
spin = eDP-1, bottom-up,exec, $keyboard
spin = eDP-1, normal, exec, killall $keyboard
