#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = swww-daemon &
exec-once = hyprsunset
exec-once = sleep 2 && swayosd-server
exec = hyprpm reload -n
exec = hyprspin
exec-once = cliphist wipe; wl-paste --watch cliphist store
exec-once = python3 /home/lev15/z.startpage/scripts/media-bridge.py
exec-once = python3 /home/lev15/z.startpage/scripts/stats-bridge.py
exec-once = snappy-switcher --daemon
exec-once = nwg-dock-hyprland -i 24 -w 5 -ml 10 -mr 10 -mb 10 -x -ico ~/.config/nwg-dock-hyprland/icons/search-icon.svg -a center -lp start -c "/bin/bash /home/lev15/.config/hypr/scripts/rofi-toggle.sh" -d
exec-once = hyprspin
exec-once = fcitx5
exec-once = quickshell -p ~/.config/quickshell/island/shell.qml
