##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Blur wlogout
layerrule {
  name = layerrule-3
  blur = on
  animation = fade
  match:namespace = logout_dialog
}

windowrule {
  name = windowrule-1
  float = on
  match:class = org.pulseaudio.pavucontrol
  match:title = Volume Control
}

windowrule {
  name = windowrule-2
  float = on
  match:class = com.network.manager
  match:title = Network Manager
}

windowrule {
  name = windowrule-3
  float = on 
  match:class = io.github.kaii_lb.Overskride
  match:title = overskride
}

windowrule {
  name = windowrule-4
  float = on
  match:class = com.github.hyprmod
  match:title = HyprMod
}

# music_vis
windowrule {
  name = music-vis-float
  float = on
  pin = on
  no_initial_focus = on
  size = 700 350
  move = 12 720
  border_size = 0
  no_shadow = on
  match:class = ^(music_vis)$
}

# CS2
windowrule {
  name = cs2-immediate
  immediate = on
  match:class = ^(cs2)$
}

# App Launcher (rofi)
windowrule {
  name = app-launcher
  float = on
  center = on
  size = 1200 600
  animation = slide
  match:title = ^(app-launcher)$
}

layerrule {
    name = qs-master-noblur
    match:title = qs-master
    blur = off
}

windowrule {
    name = qs-master-xray
    match:title = qs-master
    xray = off
    workspace = special:hidden
}

windowrule = float on, match:title ^qs-master$
windowrule = pin on, match:title ^qs-master$
windowrule = no_shadow on, match:title ^qs-master$
windowrule = border_size 0, match:title ^qs-master$
windowrule = move 999999 999999, match:title ^qs-master$
windowrule = no_initial_focus on, match:title ^qs-master$
windowrule = workspace 99 silent, match:title ^qs-master$

windowrule=match:title ^qs-master$, hyprbars:no_bar on
