plugin {
    borders-plus-plus {
        add_borders = 2
        col.border_1 = rgb(b5c9e8)
        col.border_2 = rgb(c9b5e8)
        border_size_1 = 2
        natural_rounding = yes
    }

    hyprbars {
        bar_height = 15
        bar_color = rgb(2a2a3d)
        bar_blur = true

        bar_title_enabled = true
        bar_text_size = 8
        bar_text_font = noto sans

        bar_text_align = center
        bar_buttons_alignment = left

        bar_padding = 8
        bar_button_padding = 4

        col.text = rgb(e8d5f0)

        hyprbars-button = rgb(f4a7b9), 10, , hyprctl dispatch killactive
        hyprbars-button = rgb(f9d8a0), 10, , ~/.config/hypr/scripts/hyprbars-minimize.sh
        hyprbars-button = rgb(a8d8b0), 10, , hyprctl dispatch fullscreen 1

        on_double_click = hyprctl dispatch fullscreen

	bar_rules = class:^org.quickshell$, noblur
    }

    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(1e1e2e)
        workspace_method = first 1
        skip_empty = true
    }

 } 
